name: e_commerce
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # utility packages
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  lottie: ^3.0.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.4
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0

  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # state management
  get: ^4.6.6
  get_storage: ^2.1.1

  # firebase
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.5
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  google_sign_in: ^6.2.1

  # product specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic

    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica_regular.ttf
          weight: 400
        - asset: assets/fonts/coolvetica_regular_italic.ttf
          weight: 400
          style: italic


