 // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN_r2HZ9AXfzbNRlqJNrJFRVHlzeEL198',
    appId: '1:817692559998:web:32a4af867b010bc0ed662f',
    messagingSenderId: '817692559998',
    projectId: 'ecommerce-37f21',
    authDomain: 'ecommerce-37f21.firebaseapp.com',
    storageBucket: 'ecommerce-37f21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANmZpYgnUuQwbnqJX58e_OgfH34LIb3LQ',
    appId: '1:817692559998:android:e6baa8e526171922ed662f',
    messagingSenderId: '817692559998',
    projectId: 'ecommerce-37f21',
    storageBucket: 'ecommerce-37f21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVmF9wYu46VMDG9qPBGwpLVJwK2v1UeMU',
    appId: '1:817692559998:ios:c374041d2cce58caed662f',
    messagingSenderId: '817692559998',
    projectId: 'ecommerce-37f21',
    storageBucket: 'ecommerce-37f21.appspot.com',
    iosBundleId: 'com.drsync.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVmF9wYu46VMDG9qPBGwpLVJwK2v1UeMU',
    appId: '1:817692559998:ios:a7187e6b7939ac69ed662f',
    messagingSenderId: '817692559998',
    projectId: 'ecommerce-37f21',
    storageBucket: 'ecommerce-37f21.appspot.com',
    iosBundleId: 'com.drsync.eCommerce.RunnerTests',
  );
}
